#!/bin/sh

usage(){
    cat <<HELP
task -- Shell script used to interact with the task server

USAGE: task [add|list|done|update|delete] ["task title"] [due_date] [--expiring-today] [task_id_for_done]

EXAMPLES: 
./tasks add "task title x" 08/11/2022
./tasks list
./tasks list --expiring-today
./tasks done 3

HELP
    exit 0
}

function print_out {
   local MESSAGE="${@}"
    echo "${MESSAGE}"
}

[ $# -lt 1 ] && usage

action=$1

case $1 in
    add)
        [ $# -ne 3 ] && usage
        TITLE=$2
        DUE_DATE=`date --date ${3} --iso-8601=seconds`
        echo "==="
        echo $DUE_DATE
        echo "==="
        if [[ $? -ne 0 ]];then
            print_out "INVALID DATE."
            exit 1
        fi
        print_out "Add a task: "
        curl -X POST -H "Content-Type: application/json" -d '{
            "title": "'"$TITLE"'",
            "due_date": "'"$DUE_DATE"'"
        }' http://localhost:5100/task -v
        exit 0
      ;;
    list)
        if [[ $# -eq 1 ]]; then
            curl -X GET http://localhost:5100/tasks
            exit 0
        elif [[ $# -eq 2 ]]; then
            if [[ $3 -eq "--expiring-today" ]];then
                curl http://localhost:5100/tasks/expire-in-days/0 -v
            else
                curl http://localhost:5100/tasks/expire-in-days/$2 -v
            fi
            exit 0
        fi
      ;;
    done)
        if [[ $# -ne 2 ]]; then
            echo "need task id to toggle done."
            exit 1
        else
            curl -X PUT http://localhost:5100/task/$2/toggle -v
        fi
      ;;
    *)
      print_out "...Invalid option..."
      usage
      ;;
esac


